### ISSUE TITLE
load plugin failed

### ISSUE THREAD

**Issue by Haocen2004** [kmcsr/kpi_mcdr#1]
```
[MCDR] [2023-08-27 00:32:58] [MainThread/INFO]: MCDReforged正于Python 3.10.12环境中运行
[MCDR] [2023-08-27 00:32:58] [TaskExecutor/INFO]: 刷新所有插件中
[MCDR] [2023-08-27 00:32:58] [TaskExecutor/INFO]: 插件 kpi@1.4.7 已加载
[MCDR] [2023-08-27 00:32:58] [TaskExecutor/INFO]: 插件 crash_restart@1.0.0 已加载
[MCDR] [2023-08-27 00:32:58] [TaskExecutor/INFO]: 插件 player_last_play@1.0.3 已加载
[MCDR] [2023-08-27 00:32:58] [TaskExecutor/INFO]: 插件 loginproxy@0.6.1 已加载
[MCDR] [2023-08-27 00:32:58] [TaskExecutor/INFO]: 插件 mcdreforged_plugin_manager@2.0.0 已加载
[MCDR] [2023-08-27 00:32:58] [TaskExecutor/INFO]: 插件 daycount_nbt@2.2.1 已加载
[MCDR] [2023-08-27 00:32:58] [TaskExecutor/INFO]: 插件 online_player_api@1.0.0 已加载
[MCDR] [2023-08-27 00:32:58] [TaskExecutor/INFO]: 插件 auto_plugin_reloader@1.1.3 已加载
[MCDR] [2023-08-27 00:32:58] [TaskExecutor/INFO]: 插件 delayexe@1.3.0 已加载
[MCDR] [2023-08-27 00:32:58] [TaskExecutor/INFO]: 插件 join_motd@1.3.0 已加载
[MCDR] [2023-08-27 00:32:58] [TaskExecutor/INFO]: 插件 better_backup@2.1.5 已加载
[MCDR] [2023-08-27 00:32:58] [TaskExecutor/INFO]: 插件 stats_helper@7.5.1 已加载
[MCDR] [2023-08-27 00:32:58] [TaskExecutor/INFO]: 插件 minecraft_data_api@1.5.0 已加载
[MCDR] [2023-08-27 00:32:58] [TaskExecutor/INFO]: 插件 seed@1.2.0 已加载
[MCDR] [2023-08-27 00:32:58] [TaskExecutor/INFO]: 插件 here@1.2.2 已加载
[MCDR] [2023-08-27 00:32:58] [TaskExecutor/INFO]: 插件 beep@1.1.0 已加载
[MCDR] [2023-08-27 00:32:58] [TaskExecutor/INFO]: 插件 smart_servertime@1.3.0 已加载
[MCDR] [2023-08-27 00:32:58] [TaskExecutor/INFO]: 插件 gamemode@1.0.1 已加载
[MCDR] [2023-08-27 00:32:58] [TaskExecutor/ERROR]: Fail to load the entry point of kpi@1.4.7
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/mcdreforged/plugin/type/multi_file_plugin.py", line 66, in _on_ready
    self._load_entry_instance()
  File "/usr/local/lib/python3.10/dist-packages/mcdreforged/plugin/type/regular_plugin.py", line 66, in _load_entry_instance
    self.entry_module_instance = self._import_entrypoint_module()
  File "/usr/local/lib/python3.10/dist-packages/mcdreforged/plugin/type/multi_file_plugin.py", line 34, in _import_entrypoint_module
    mod = importlib.import_module(self.get_metadata().entrypoint)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "plugins/KPI-v1.4.7.mcdr/kpi/__init__.py", line 4, in <module>
    from . import config
  File "plugins/KPI-v1.4.7.mcdr/kpi/config.py", line 8, in <module>
    from typing import get_type_hints, Any, Union, Optional, ClassVar, Self
ImportError: cannot import name 'Self' from 'typing' (/usr/lib/python3.10/typing.py)
```

**Comment by zyxkad** [comment]
Hmm, don't we have Self in python 10?

**Comment by zyxkad** [comment]
Fixed in <https://github.com/kmcsr/kpi_mcdr/releases/tag/v1.4.8>
